export const HOME_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const AUTH_ROUTE = '/auth'
export const MAP_ROUTE = '/map'
export const CHAT_ROUTE = '/chat'
export const NOT_FOUND_ROUTE = '*'